name: Deploy lilbarberia app

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 Configura credenciales AWS (usa los SECRETS del repo)
    

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: |
          cd terraform 
          terraform init 

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_DEFAULT_REGION: us-east-1
            TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
      #main

      - name: terraform Apply for prod
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform
          terraform apply -var "stage_name=prod" -var "deploy_id=lilbarberia" -auto-approve -input=false

        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_DEFAULT_REGION: us-east-1
            TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}