name: Deploy silviobarberia App

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 Configura credenciales de AWS ANTES de terraform init
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init -reconfigure -input=false

      # --- Dev ---
      - name: Terraform Plan for Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform plan -var "stage_name=dev"

      - name: Terraform Apply for Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -var "stage_name=dev" -auto-approve

      # --- Prod ---
      - name: Terraform Plan for Prod
        if: github.ref == 'refs/heads/main'
        run: terraform plan -var "stage_name=prod"

      - name: Terraform Apply for Prod
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var "stage_name=prod" -auto-approve
